name: Publish to PyPI on Release (Trusted Publishing)

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Upload via OIDC
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # Required for OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build distributions
        run: |
          python -m build
          ls -l dist

      - name: Publish (OIDC / Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        # No password needed when OIDC publisher is configured
        # You can still add: with: skip-existing: true  if desired
